import { Link, useLocation } from "wouter";

type Lang = "en" | "fr" | "es" | "de" | "nl" | "it";
const supported: Lang[] = ["en", "fr", "es", "de", "nl", "it"];
const content: Record<Lang, { title: string; intro: string; sections: [string, string][]; back: string }> = {
  en: { title: "Privacy for private enquiries", intro: "A short, plain-language note about the details you share when requesting the Jávea Bliss presentation.", back: "Return to private access", sections: [["Purpose", "We use your details to verify your request, send the access code and provide the private property presentation you requested."], ["What we collect", "Your name, email address, telephone number, buyer type, agency name when relevant, preferred language, IP address, approximate town and country, consent record and access/download history."], ["Legal basis", "We process this information to take steps at your request and, where indicated, on the basis of your consent. You may withdraw consent at any time by contacting us."], ["Recipients and security", "Details are accessed only by the Jávea Bliss team and trusted providers needed to deliver email, locate IP addresses and provide secure documents. We use reasonable technical and organisational safeguards."], ["Retention", "Verified enquiries are retained for 12 months to support a considered follow-up. Unverified requests are cleaned up within 48 hours. Download records follow the same retention period."], ["Your rights", "You may request access, correction, deletion, restriction or portability, or object to processing. Contact admin@javeabliss.com and we will respond as required."]] },
  fr: { title: "Confidentialité des demandes privées", intro: "Une note simple sur les informations partagées pour demander la présentation Jávea Bliss.", back: "Retour à l’accès privé", sections: [["Finalité", "Nous utilisons vos coordonnées pour vérifier votre demande, envoyer le code et fournir la présentation privée demandée."], ["Données collectées", "Nom, e-mail, téléphone, type d’acheteur, agence le cas échéant, langue, adresse IP, ville et pays approximatifs, consentement et historique d’accès et de téléchargement."], ["Base légale", "Le traitement répond à votre demande et, lorsque précisé, à votre consentement. Vous pouvez le retirer à tout moment."], ["Destinataires et sécurité", "Seule l’équipe Jávea Bliss et les prestataires nécessaires à l’envoi d’e-mails, à la localisation des adresses IP et aux documents sécurisés y ont accès. Des mesures de sécurité raisonnables sont appliquées."], ["Conservation", "Les demandes vérifiées sont conservées 12 mois pour assurer un suivi attentif. Les demandes non vérifiées sont supprimées sous 48 heures."], ["Vos droits", "Vous pouvez demander l’accès, la rectification, l’effacement, la limitation ou la portabilité. Contact : admin@javeabliss.com."]] },
  es: { title: "Privacidad de las solicitudes privadas", intro: "Una explicación clara sobre los datos que comparte al solicitar la presentación de Jávea Bliss.", back: "Volver al acceso privado", sections: [["Finalidad", "Usamos sus datos para verificar la solicitud, enviar el código y facilitar la presentación privada solicitada."], ["Datos que recogemos", "Nombre, correo, teléfono, tipo de comprador, agencia si corresponde, idioma, dirección IP, localidad y país aproximados, consentimiento e historial de acceso y descargas."], ["Base legal", "Tratamos los datos para atender su solicitud y, cuando se indica, con su consentimiento. Puede retirarlo en cualquier momento."], ["Destinatarios y seguridad", "Solo acceden el equipo de Jávea Bliss y proveedores necesarios para correos, localización de IP y documentos seguros. Aplicamos medidas razonables de seguridad."], ["Conservación", "Las solicitudes verificadas se conservan 12 meses. Las solicitudes no verificadas se eliminan en un plazo de 48 horas."], ["Sus derechos", "Puede solicitar acceso, rectificación, supresión, limitación o portabilidad. Contacto: admin@javeabliss.com."]] },
  de: { title: "Datenschutz für private Anfragen", intro: "Eine klare Zusammenfassung der Angaben, die Sie für die Jávea Bliss Präsentation teilen.", back: "Zurück zum privaten Zugang", sections: [["Zweck", "Wir verwenden Ihre Angaben, um Ihre Anfrage zu prüfen, den Zugangscode zu senden und die gewünschte private Präsentation bereitzustellen."], ["Erhobene Daten", "Name, E-Mail, Telefon, Käufertyp, gegebenenfalls Agenturname, Sprache, IP-Adresse, ungefähre Stadt und Land, Einwilligung sowie Zugangs- und Downloadverlauf."], ["Rechtsgrundlage", "Die Verarbeitung erfolgt auf Ihre Anfrage hin und, soweit angegeben, auf Grundlage Ihrer Einwilligung. Sie können diese jederzeit widerrufen."], ["Empfänger und Sicherheit", "Zugriff haben nur das Jávea Bliss-Team und notwendige Dienstleister für E-Mail, IP-Lokalisierung und sichere Dokumente. Wir setzen angemessene Schutzmaßnahmen ein."], ["Aufbewahrung", "Bestätigte Anfragen werden 12 Monate aufbewahrt. Nicht bestätigte Anfragen werden innerhalb von 48 Stunden gelöscht."], ["Ihre Rechte", "Sie können Auskunft, Berichtigung, Löschung, Einschränkung oder Übertragbarkeit verlangen. Kontakt: admin@javeabliss.com."]] },
  nl: { title: "Privacy bij privéaanvragen", intro: "Een heldere uitleg over de gegevens die u deelt voor de Jávea Bliss-presentatie.", back: "Terug naar privétoegang", sections: [["Doel", "We gebruiken uw gegevens om uw aanvraag te verifiëren, de code te sturen en de gevraagde privépresentatie te leveren."], ["Gegevens", "Naam, e-mail, telefoon, type koper, bureau indien relevant, taal, IP-adres, geschatte plaats en land, toestemming en toegangs- en downloadgeschiedenis."], ["Rechtsgrond", "We verwerken gegevens op uw verzoek en, waar aangegeven, met uw toestemming. U kunt die altijd intrekken."], ["Ontvangers en beveiliging", "Alleen het Jávea Bliss-team en noodzakelijke dienstverleners voor e-mail, IP-locatie en beveiligde documenten hebben toegang. We gebruiken passende beveiliging."], ["Bewaartermijn", "Geverifieerde aanvragen bewaren we 12 maanden. Niet-geverifieerde aanvragen worden binnen 48 uur verwijderd."], ["Uw rechten", "U kunt inzage, correctie, verwijdering, beperking of overdraagbaarheid vragen. Contact: admin@javeabliss.com."]] },
  it: { title: "Privacy per richieste private", intro: "Una spiegazione chiara dei dati condivisi per richiedere la presentazione Jávea Bliss.", back: "Torna all’accesso privato", sections: [["Finalità", "Usiamo i dati per verificare la richiesta, inviare il codice e fornire la presentazione privata richiesta."], ["Dati raccolti", "Nome, e-mail, telefono, tipo di acquirente, agenzia se pertinente, lingua, indirizzo IP, città e paese approssimativi, consenso e cronologia di accessi e download."], ["Base giuridica", "Trattiamo i dati per rispondere alla richiesta e, quando indicato, sulla base del consenso, che può essere revocato."], ["Destinatari e sicurezza", "L’accesso è limitato al team Jávea Bliss e ai fornitori necessari per e-mail, localizzazione IP e documenti sicuri. Adottiamo misure ragionevoli."], ["Conservazione", "Le richieste verificate vengono conservate 12 mesi. Le richieste non verificate vengono eliminate entro 48 ore."], ["I suoi diritti", "Può chiedere accesso, rettifica, cancellazione, limitazione o portabilità. Contatto: admin@javeabliss.com."]] },
};

export default function SalesPrivacy() {
  const [location] = useLocation();
  const pathLanguage = location.split("/").filter(Boolean)[0];
  const lang = supported.includes(pathLanguage as Lang) ? pathLanguage as Lang : "en";
  const page = content[lang];
  return <main className="min-h-[100dvh] bg-[#f4f0e8] px-6 py-8 text-[#24352f] md:px-12">
    <header className="mx-auto flex max-w-4xl justify-between"><Link href={lang === "en" ? "/" : `/${lang}/`} className="font-montserrat text-sm tracking-[.22em]">JÁVEA BLISS</Link><span className="font-montserrat text-[10px] uppercase tracking-[.2em] text-[#68756e]">{lang}</span></header>
    <article className="mx-auto max-w-3xl py-20"><p className="font-montserrat text-[10px] uppercase tracking-[.25em] text-[#a57a4c]">{privateAccessLabel(lang)}</p><h1 className="mt-5 max-w-2xl font-serif text-5xl leading-none md:text-6xl">{page.title}</h1><p className="mt-7 max-w-xl text-lg leading-8 text-[#68756e]">{page.intro}</p><div className="mt-14 border-t border-[#c9c2b6]">{page.sections.map(([heading, text]) => <section key={heading} className="border-b border-[#c9c2b6] py-7"><h2 className="font-serif text-2xl">{heading}</h2><p className="mt-3 max-w-2xl text-sm leading-7 text-[#53635c]">{text}</p></section>)}</div><a href="mailto:admin@javeabliss.com" className="mt-10 inline-block text-sm text-[#a57a4c] underline underline-offset-4">admin@javeabliss.com</a><br /><Link href={lang === "en" ? "/for-sale" : `/${lang}/for-sale`} className="mt-8 inline-block text-xs uppercase tracking-widest text-[#24352f] underline underline-offset-4">{page.back}</Link></article>
  </main>;
}

function privateAccessLabel(lang: Lang) {
  return ({
    en: "Private access",
    fr: "Accès privé",
    es: "Acceso privado",
    de: "Privater Zugang",
    nl: "Privétoegang",
    it: "Accesso privato",
  } as Record<Lang, string>)[lang];
}