// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/at-glance-redesign/Current.tsx": () => import("../components/mockups/at-glance-redesign/Current.tsx"),
  "./components/mockups/at-glance-redesign/ModernCoastal.tsx": () => import("../components/mockups/at-glance-redesign/ModernCoastal.tsx")
};
